# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import shutil
from pytube import YouTube
from moviepy.editor import *
from PyQt5.QtWidgets import QMessageBox, QApplication,QProgressBar
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ytlinkinput = QtWidgets.QLineEdit(self.centralwidget)
        self.ytlinkinput.setGeometry(QtCore.QRect(30, 110, 750, 31))
        self.ytlinkinput.setPlaceholderText("輸入Youtube影片網址") #為輸入框設置提示文字
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ytlinkinput.setFont(font)
        self.ytlinkinput.setText("")
        self.ytlinkinput.setCursorPosition(0)
        self.ytlinkinput.setObjectName("ytlinkinput")
        self.windowtitle = QtWidgets.QLabel(self.centralwidget)
        self.windowtitle.setGeometry(QtCore.QRect(240, 40, 500, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.windowtitle.setFont(font)
        self.windowtitle.setObjectName("windowtitle")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 170, 421, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mp3btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.mp3btn.setFont(font)
        self.mp3btn.setObjectName("mp3btn")
        self.mp3btn.clicked.connect(self.mp3) # 為轉mp3按鈕綁定點擊事件
        self.horizontalLayout.addWidget(self.mp3btn)
        self.mp4btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.mp4btn.setFont(font)
        self.mp4btn.setObjectName("mp4btn")
        self.mp4btn.clicked.connect(self.mp4) # 為轉mp4按鈕綁定點擊事件
        self.horizontalLayout.addWidget(self.mp4btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.label = QtWidgets.QLabel(MainWindow)   # 在 Form 裡加入標籤
        

        self.label.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.windowtitle.setText(_translate("MainWindow", "Youtube轉MP3 MP4 轉換器"))
        self.mp3btn.setText(_translate("MainWindow", "轉MP3"))
        self.mp4btn.setText(_translate("MainWindow", "轉MP4"))

    def mp3(self):
        mp4_file= self.mp4(callbymp3=True)
        
        if mp4_file:
            mp3_file = mp4_file.replace('mp4','mp3')
            video_1 = VideoFileClip(mp4_file)
            audio_1 = video_1.audio
            audio_1.write_audiofile(mp3_file)
            video_1.close()
            audio_1.close()
            os.remove(mp4_file)      
            print("下載完成")
            self.label.setText('完成轉檔')
            self.label.setStyleSheet('''
                color:green;
                font-size:24px;
                font-weight:bold;
            ''')
            self.label.setGeometry(350, 200, 455, 30)  
        else:
            print('檔案下載失敗')

    def mp4(self,callbymp3=False):
        try :
            url = self.ytlinkinput.text()
            if len(url.strip())==0:
                mbox = QMessageBox(MainWindow)       # 加入對話視窗
                mbox.warning(MainWindow, 'warning', '請先輸入youtube連結')  # 開啟資訊通知的對話視窗，標題 info，內容 hello
                self.label.hide()
                return False
            self.label.setText('正在轉檔中....')     # 設定標籤文字
            self.label.setGeometry(300, 200, 455, 30)
            self.label.setStyleSheet('''
                color:purple;
                font-size:24px;
                font-weight:bold;
            ''')
            self.label.show()
            QApplication.processEvents()  # 强制处理待处理的事件并更新界面
            streams = YouTube(url).streams.filter(progressive=True)
            res = int(streams.first().resolution.replace('p',''))
            stream = None
            for i in streams:
                if int(i.resolution.replace('p',''))>res:
                    stream = i
            print(stream)
            print(f'stream total size :{stream.filesize}')
        except Exception as e:
            print("檔案處理有誤")
            print(f"原因:{e}")
        else:
            try:
                yt = stream.download()
            except Exception as e:
                print('檔案下載失敗')
                print(f"失敗原因:{e}")
            else :
                if not callbymp3:
                    print("下載完成")
                    self.label.setText('完成轉檔')
                    self.label.setStyleSheet('''
                        color:green;
                        font-size:24px;
                        font-weight:bold;
                    ''')
                    self.label.setGeometry(350, 200, 455, 30)

                return yt


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
